@extends('layouts.staff')
@section('title')
Roster Admin
@stop
@section('content')
@include('includes.nav._roster')
    @if(!$view || $view == 'roster')
    @include('staff.roster.roster')
    @elseif($view === 'visitor')
    @include('staff.roster.visitor')
    @elseif($view === 'staff')
    @include('staff.roster.staff')
    @elseif($view === 'adopt')
    @include('staff.roster.adopt')
    @elseif($view === 'inactive')
    @include('staff.roster.inactive')
    @elseif($view === 'controller')
    @include('staff.roster.addcontroller')
    @elseif($view === 'staff')
    @include('staff.roster.addstaff')
    @elseif($view === 'groups')
    @include('staff.roster.groups.index')
    @elseif($view === 'remove')
    @include('staff.roster.remove')
    @endif
@stop
